version: '3.1'

services:
  db:
    image: postgres:10
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 415782
    volumes:
      - projeto-base:/var/lib/postgresql

volumes:
  projeto-base: