# SERVIDOR
server:
  servlet:
    context-path: /projeto-backend
  port: 8080

spring:
  application:
    name: projeto-base
  profiles:
    active: dev
  # configurando o Spring Boot Admin Server
  #boot:
    #admin:
      #client:
        #url: http://localhost:8081
  #CONFIGURACAO DO BANCO POSTGRES
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://35.193.157.60:5432/projeto
    username: postgres
    password: 415782
  h2:
    console:
      enabled: true
      path: /h2

  #ATIVANDO MIGRACAO DO FLYWAY
  flyway:
    enabled: true
    baseline-on-migrate: true

  #NAO ACEITAR ATRIBUTOS DESCONHECIDOS PELA API
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false

management:
  security:
    enabled: false
  #alem do health e do info ele sempre vai export todos endpoints disponiveis
  endpoints:
    web:
      exposure:
        include: "*"
  #indica que health deve mostrar detalhes sempre
  endpoint:
    health:
      show-details: always
# puxa informacoes do projeto do pom.xml
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

#CONFIGURA??ES DE SERVIDOR DE EMAIL
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=com1.com3@gmail.com
#spring.mail.password=415782@Davi
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true



