CREATE TABLE TB001_ENDERECO(
    CO_ENDERECO SERIAL PRIMARY KEY,
    CO_CEP VARCHAR(10) NOT NULL,
    NO_LOGRADOURO VARCHAR(100) NOT NULL,
    NU_NUMERO VARCHAR(10) NOT NULL,
    NO_COMPLEMENTO VARCHAR(100),
    NO_BAIRRO VARCHAR(100) NOT NULL,
    NO_CIDADE VARCHAR(100) NOT NULL,
    NO_UF CHAR(2) NOT NULL,
    CO_IBGE VARCHAR(20) NOT NULL
)