CREATE TABLE TB004_EMPRESA(
    CO_EMPRESA SERIAL PRIMARY KEY,
    CO_CNPJ VARCHAR(14) NOT NULL,
    NO_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    NO_NOME_FANTASIA VARCHAR(100) NOT NULL,
    DE_SITUACAO VARCHAR(60) NOT NULL,
    NO_NATUREZA_JURIDICA VARCHAR(150),
    DT_ABERTURA DATE,
    NO_TIPO_EMPRESA VARCHAR(60),
    DE_PORTE VARCHAR(60),
    DE_STATUS VARCHAR(60),
    CONTATO_CO INT,
    ENDERECO_CO INT,
    FOREIGN KEY (CONTATO_CO) REFERENCES TB002_CONTATO (CO_CONTATO),
    FOREIGN KEY (ENDERECO_CO) REFERENCES TB001_ENDERECO (CO_ENDERECO)
)