CREATE TABLE TB005_USUARIO(
    CO_USUARIO SERIAL PRIMARY KEY,
    NO_NOME VARCHAR(60) NOT NULL,
    NU_CPF VARCHAR(14) NOT NULL,
    CO_SENHA VARCHAR(150) NOT NULL,
    DE_EMAIL VARCHAR(60) NOT NULL,
    EMPRESA_CO INT NOT NULL,
    FOREIGN KEY (EMPRESA_CO) REFERENCES TB004_EMPRESA (CO_EMPRESA)
)