CREATE TABLE TB008_AUDITORIA(
    CO_AUDITORIA SERIAL PRIMARY KEY,
    NO_FUNCIONALIDADE VARCHAR(50) NOT NULL,
    NO_EVENTO VARCHAR(50) NOT NULL,
    DT_DATA_HORA TIMESTAMP NOT NULL,
    NO_USUARIO VARCHAR(50) NOT NULL,
    NU_HOSTNAME VARCHAR(20) NOT NULL
)